// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _714b9f8fd47e343158014373676f77d0_97320cdaa6f641c98d6f57d68520c0e5 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector3 spawnPosition;
        }

        public static unsafe _714b9f8fd47e343158014373676f77d0_97320cdaa6f641c98d6f57d68520c0e5 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 12) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 12) " +
                    "for command with ID 17");
            }

            var orig = new _714b9f8fd47e343158014373676f77d0_97320cdaa6f641c98d6f57d68520c0e5();
            var comp = (Interop*)data;
            orig.spawnPosition = comp->spawnPosition;
            return orig;
        }

        public Vector3 spawnPosition;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 17;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _714b9f8fd47e343158014373676f77d0_97320cdaa6f641c98d6f57d68520c0e5(
        Entity entity,
        Vector3 spawnPosition
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.spawnPosition = spawnPosition; 
        }
        
        public static void Serialize(_714b9f8fd47e343158014373676f77d0_97320cdaa6f641c98d6f57d68520c0e5 commandData, IOutProtocolBitStream bitStream)
        {
            var converted_spawnPosition = commandData.spawnPosition.ToCoreVector3();
            bitStream.WriteVector3(converted_spawnPosition, FloatMeta.NoCompression());
        }
        
        public static _714b9f8fd47e343158014373676f77d0_97320cdaa6f641c98d6f57d68520c0e5 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var converted_spawnPosition = bitStream.ReadVector3(FloatMeta.NoCompression());
            var dataspawnPosition = converted_spawnPosition.ToUnityVector3();
    
            return new _714b9f8fd47e343158014373676f77d0_97320cdaa6f641c98d6f57d68520c0e5()
            {
                Entity = entity,
                Routing = target,
                spawnPosition = dataspawnPosition
            };   
        }
    }

}
